# Workflow for building and testing eventuals on macOS, Ubuntu and Windows.  
name: Build and Run all tests

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Build on macos or ubuntu
        if: ${{ matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest' }}
        run: echo "building..."
      
      - name: Build on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: echo "building..."
      
