name: Check clang-format on macOS

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main" 

jobs:
  check_clang_format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check clang-format
        run: |
          chmod +x check.sh
          ./check.sh
        shell: bash    
