name: Check clang-format on macOS

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main" 

jobs:
  check_clang_format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check clang-format
        run: |
          which clang-format
          if [[ $? != 0 ]]; then
            echo "Failed to find 'clang-format' (please install it)"
            exit 1
          fi
        shell: bash    
