name: Check clang-format on macOS

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main" 

jobs:
  check_clang_format:
    runs-on: -latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check clang-tidy
        run: which clang-tidy-12
      
      - name: Check clang-format version
        id: clang_format_status
        run: clang-format --version
        continue-on-error: true
      
      - name: Exit if we do not have clang-format installed
        if: steps.clang_format_status.outcome != 'success'
        run:  |
          echo "There is no clang-format installed."
          exit 1
