# Workflow for building and testing eventuals on macOS, Ubuntu and Windows.  
name: Build and Run all tests

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
  
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Install clang-format
        run: brew install clang-format-13
                
