name: Check clang-format on macOS

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "main" 

jobs:
  check_clang_format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check clang-format version
        id: clang_format_status
        run: |
          status=$(clang-format --version) &&
          echo "::set-output name=status::$status"
        continue-on-error: true
      
      - name: Exit if we do not have clang-format installed
        if: steps.clang_format_status.outputs.status != 0
        run: exit 1
          
          
