# Workflow for building and testing eventuals on macOS, Ubuntu and Windows.  
name: Build and Run all tests

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**.md"
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      # Checkout the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v2

      - name: Install clang-tidy
        run: | 
          cd $(brew --prefix llvm)/bin 
          clang-tidy --version
      
